### ISSUE TITLE
Adaptation to Instax SQUARE Link

### ISSUE THREAD

**Issue by geffaelden** [javl/InstaxBLE#4] opened 2022-12-28 06:07 UTC
I was wondering if the same code can be adapted to the SQUARE Link? https://instax.com/square_link/en/

**Comment by javl** [comment] 2022-12-28 07:30
I have no way of testing this (I don't have that printer) but I expect it to work pretty much the same way, except with a larger image. The mini link uses a 600x800 image so I think the square would use 800x800?

Though I can also imagine the code being slightly different as the same filesize limit but a larger image would mean a lower quality image will be printed.

If you have an Android phone you could try to record the bluetooth interaction and we can see what happens.

**Comment by javl** [comment] 2023-03-26 15:03
@geffaelden If you're on IOS and have a Mac you can also use their PacketLogger tool to record the data between your phone and the printer. Using those logs I should be able to see if / what needs to be changed in to code to support the SQUARE link.

Basically the steps are:
1. Download a profile file from Apple, install this on your IOS device
2. Download Packet Logger on your Mac
3. Connect your IOS device using the cable and in Packet Logger starts a new IOS trace
4. Clear all data, print your image, stop the logging and save the result

Pretty clear steps can be found here: https://www.bluetooth.com/blog/a-new-way-to-debug-iosbluetooth-applications/

**Comment by geffaelden** [comment] 2023-03-27 01:18
@javl I've done this but can't seem to figure out which log is for the image printing

**Comment by javl** [comment] 2023-03-27 07:55
@geffaelden On what platform? If you used Packet Logger with IOS you can just start recording, do the printing and stop recording, and send that complete file. There might be some other stuff in there but that doesn't matter, I can filter out the printer part.

**Comment by javl** [comment] 2023-03-27 14:47
@geffaelden Took a very quick look and it seems it shouldn't be too hard to adapt my code to work, just need to find the time ;) Thanks for the file!

**Comment by javl** [comment] 2023-03-29 11:35
@geffaelden Something is different compared to the way the Mini Link prints its images. Managed to get a 800x800 px image from your logs, but there are some glitches. Do you still have the image file you used for printing? If so I could compare it against what I get from to logs to see what is happening (the app sends over the orignal image, so by comparing the original bytes with the logs I should be able to see what's changed).

**Comment by geffaelden** [comment] 2023-03-29 14:17
Heres the test image I printed 

![New Project](https://user-images.githubusercontent.com/34681985/228567500-0fb05635-e304-488b-b46c-3875695c7eae.png)

**Comment by javl** [comment] 2023-03-29 14:30
Ok, that might explain something: the other printer only supports .jpg but this is .png (though the header in the logs seems to suggest jpg).

Thanks for the file.

**Comment by javl** [comment] 2023-03-29 15:57
It seems you are allowed to select mode image types (jpg, png and some newer formats used on IOS and Android) than with the Mini Link (jpg only) but the app just converts it into a jpg to send to the printer. There was some error in my parser and now I'm able to extract your image from the logs, meaning I should be able to adapt my code to send your image to the printer as well. Stay tuned ;)

Not sure what would be the best approach: having the user set a device type (something like `instax.set_model(square)` or detect the model based on the image (600x800 is mini link, 800x800 is square, and 800x600 probably is wide?)

**Comment by javl** [comment] 2023-04-03 21:18
@geffaelden I think the fix to support the square is simple: can you try replacing `chunkSize = 900` with `chunkSize = 1808` and try printing again?

**Comment by linssenste** [comment] 2023-04-12 14:01
I successfully printed an image on the Instax Square Link 🥳 Using a chunkSize of 1808 did the trick! Initially, I encountered an issue with the incorrect image size, which was caused by faulty compression (see image 🤦🏼‍♂️). However, using an 800x800 JPEG resolved the problem. I developed my own implementation in TypeScript, utilizing the Bluetooth Web API, and drew significant inspiration from your work, @javl. Thank you for your great work! 
![print_results](https://user-images.githubusercontent.com/13923365/231481174-a652d256-30c1-4b56-84ce-7683b8a52a88.png)


In addition to this, I've been working on parsing other messages of the INSTAX Protocol, such as battery status, charging status, printed images, and more. I wanted to created an alternative UI to print images with an Instax printer via a web browser. I plan to upload my code to GitHub in the coming days. 
<img width="337" alt="Bildschirm­foto 2023-04-12 um 16 00 27" src="https://user-images.githubusercontent.com/13923365/231481703-59bbcb26-8af4-4894-8e18-771b6a72b404.png">

**Comment by javl** [comment] 2023-04-12 14:41
@linssenste 
By the way, I already have some of those features in some old code:
Send a message with opcode `EventType.XYZ_AXIS_INFO`, `InfoType.BATTERY_INFO` or `InfoType.PRINTER_FUNCTION_INFO` and you can parse the results like this:

```
        header, length, op1, op2 = unpack_from('>HHBB', response)
        if (op1, op2) == EventType.XYZ_AXIS_INFO.value:
            x, y, z, o = unpack_from('<hhhB', response[6:-1])
            print(f'x: {x}, y: {y}, z: {z}, o: {o}')
            return
        elif (op1, op2) == EventType.SUPPORT_FUNCTION_INFO.value:
            infoType = InfoType(response[6])
            if infoType == InfoType.BATTERY_INFO:
                self.batteryState, self.batteryPercentage = unpack_from('>BB', response[8:10])
                print(f'battery state: {self.batteryState}, battery percentage: {self.batteryPercentage}')
                return
            elif infoType == InfoType.PRINTER_FUNCTION_INFO:
                dataByte = response[8]
                self.photosLeft = dataByte & 15
                self.isCharging = (1 << 7) & dataByte >= 1
                print(f'photos left: {self.photosLeft}, is charging: {self.isCharging}')
                return
```

**Comment by linssenste** [comment] 2023-04-16 18:54
@javl Thanks! 

I uploaded my source code in the [repository](https://github.com/linssenste/instax-link-web) and the project is accessible here: https://instax-link-web.vercel.app/

It’s currently only working with the SQUARE printer, but I have access to the mini and wide soon and will test and implement them.  🙃 

I will work with your repository as well soon, as I want to programmatically control the printers as well, so we may also close this issue then.

Btw: if you want to scale images to test with the python code, you can just download the image, it’s already compressed and resized

**Comment by javl** [comment] 2023-04-16 21:08
For the mini just use a size of 900 as in my current code. 

So we know:
Mini 600x800, 900 bytes
Square 800x800, 1808 bytes

My guess is the wide will be 800x600, 900 bytes.

**Comment by javl** [comment] 2023-04-16 21:20
@linssenste Great readme by the way (and I love Jasper the dog)

**Comment by javl** [comment] 2023-04-17 12:39
@linssenste was thinking about adding a setting to specify the printer you're using, but then I read this in your readme

`Once you connect your printer via Bluetooth, the app fetches specific details like battery status, charging state, remaining prints, and allowed image dimensions (width and height). These updates roll in every 2.5 seconds.`

I totally forgot you can just get the model type from the printer :) Way more user friendly. But could you point me towards where you get the print size from the device? All the sizes I see in your repo seem to be hard-coded?

**Comment by javl** [comment] 2023-04-18 16:23
That works perfectly. You can also get the printer type from a code it sends: the Link Mini seems to be `SP-4`, but I guess you don't really need anything beside the size it allows.

**Comment by vertgo** [comment] 2023-05-06 00:20
Trying to make this work with a raspberry pi and an instax square link, so it's been a bit painful. Right now, my main problem is during the data packing when it creates packets for printing, with an 800x800 image and a chunksize of 1808.

`self.packetsForPrinting = [
            self.create_packet(EventType.PRINT_IMAGE_DOWNLOAD_START, b'\x02\x00\x00\x00\x00\x00' + pack('>H', len(imgData)))
        ]`

I get an error: 

> Error:  'H' format requires 0 <= number <= 65535

The length of imagedata at that point is 90110, so more than the H format.

**Comment by javl** [comment] 2023-05-06 09:47
@vertgo 

Your error is 'Error: 'H' format requires 0 <= number <= 65535' which seems to be correct if the length of your data js 90110, which is more than the max allowed 65535 from the error ;)

This suggests your image is about 90kb, try saving it at a lower quality so you end up around or below 65kb. 

I've had trouble getting this to work with the Rpi so very curious to see your results. In my case it became VERY slow and I was thinking of moving back to a script that uses a bluetooth socket instead when running on a pi. Would love to get this working reliably.

**Comment by javl** [comment] 2023-05-06 09:54
@vertgo 
I was about to do some more tests on a pi. I think I mixed up some settings before: originally I used a socket with a packet size of 900, as used by the android app. Sockets didn't work on mac/windows so I moved to simplepyble but I kept the size at 900. Maybe it will run fine on the pi at 1808. The main problem was the speed, took about a minute to send one image, but at 1808 it might be way faster.

**Comment by vertgo** [comment] 2023-05-06 14:20
@javl I thought I posted last night, I got it working using 'i' instead of 'H'. It was a bit unreliable so there will have to be more tests. Would 'i' also work for the mini printer (I only have the square and the wide, about to try the wide). Doing it from pi was a bit spotty, as the simplepyble required installing from piwheels and was only compatible with bullseye

```
self.packetsForPrinting = [
            self.create_packet(EventType.PRINT_IMAGE_DOWNLOAD_START, b'\x02\x00\x00\x00\x00\x00' + pack('>i', len(imgData)))
        ]
```

**Comment by javl** [comment] 2023-05-06 14:40
@vertgo 
The `H` is an unsigned short = 2 bytes, while `i` is a 4-byte integer, so I can imagine this will give trouble at some point as it offsets the content of your packet by 2 bytes, which the code on the printer doesn't expect. 
The phone app will change the quality of the image to fit the size allowed, which is not a lot, I have to admit: even for the 600x800 of the Link Mini 65kb is pretty low res. I think I'll add an option to do this automatically to the Python script later on (which basically just saves your image with lower and lower quality over and over until it finds a quality setting that gets the image below 65kb).

If you run your Pi with a desktop you could give the site @linssenste made a try (you need to enable bluetooth in your browser's settings). It already includes the resizing. https://instax-link-web.vercel.app/

I'd love to be able to use a single bluetooth backend for all systems, but if we can't find a way to speed up the transfer, adding another layer for the socket is needed I guess, as the Pi is also my main target device. I guess we could come up with some structure that allows the user to write a single script and let the module decide what backend to use automatically.

I never made a proper tag or branch with the old version, but if you want to give it a go i think the socket was still around in commit 5f78b1261d2773fe80254f52d2212a0b0f1d0ec1 on the main branch (or otherwise just check some other old commits).

**Comment by vertgo** [comment] 2023-06-04 14:40
How did you come to the conclusion it was 1808? It seems so specific. I am trying to track down why printing from the app is SO much faster than using the library

**Comment by javl** [comment] 2023-08-09 08:44
@vertgo If you log the data transfer you can see the size of the packets it is sending. Basically it is the size of the payload minus the header (2), length (1), event code (2), checksum (1) and packet index (4). See this post for an example: https://github.com/javl/InstaxBLE/issues/9#issuecomment-1670847484

Making it faster would be amazing, but I haven't figure out how yet :disappointed:

**Comment by javl** [comment] 2023-08-09 09:13
I've created a separate issue for the speed problem, feel free to post any suggestions, test or remarks in there!

**Closed by javl** 2023-08-09 09:13 UTC
Labels: enhancement

**Comment by javl** [comment] 2023-08-09 12:41
> > Basically it is the size of the payload minus the header (2), length (1), event code (2), checksum (1) and packet index (4)
> 
> @javl , isn't the length two (2) bytes ?

You're right, its a big-endian unsigned short to be precise
https://github.com/javl/InstaxBLE/blob/f8c405108931ba4dadc74d7fed0ca309ef5f4f94/InstaxBLE.py#L303
